(()=>{
 const account=window.dashboardAccount;let busy=false;
 async function api(op,body){const r=await fetch('/api/gateway?op='+op,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(r.status===401){location.replace('/');throw new Error('Session ended.');}const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed.');return data;}
 const logout=document.createElement('button');logout.className='secondary-btn';logout.textContent='Sign out';logout.onclick=async()=>{await api('logout',{});location.replace('/');};document.querySelector('.top-actions').append(logout);
 const tick=()=>{if(document.visibilityState==='visible')api('activity',{}).catch(()=>{});};setInterval(tick,60000);document.addEventListener('visibilitychange',tick);tick();
 window.addEventListener('pageshow',()=>api('session').catch(()=>{}));
 if(account.role!=='admin')return;
 const tab=document.createElement('button');tab.className='nav-item';tab.textContent='Account Management';tab.dataset.section='accounts';document.querySelector('.nav').append(tab);
 const section=document.createElement('section');section.className='dashboard-section';section.id='accountsSection';section.innerHTML='<article class="card"><div class="card-head"><h2>Account Management</h2><button class="secondary-btn" id="accountsRefresh">Refresh</button></div><form id="accountCreate"><label>Username <input name="username" autocomplete="off" required minlength="3" maxlength="80"></label><label>Password <input name="password" type="password" autocomplete="new-password" required minlength="10" maxlength="128"></label><button class="secondary-btn">Create viewer</button></form><p id="accountsStatus" role="status"></p><div class="table-wrap"><table><thead><tr><th>Username</th><th>Role</th><th>Status</th><th>Last login</th><th>Last active</th><th>Manage</th></tr></thead><tbody id="accountsBody"></tbody></table></div><p>Last active updates once per minute while the dashboard is visible. Sessions expire after 8 hours. Password resets and disabling accounts end existing sessions.</p></article>';
 document.querySelector('main').append(section);
 tab.onclick=()=>{document.querySelectorAll('.nav-item,.dashboard-section').forEach(n=>n.classList.remove('active'));tab.classList.add('active');section.classList.add('active');document.getElementById('pageTitle').textContent='Account Management';refresh();};
 const escaped=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const when=s=>s?new Date(s).toLocaleString():'Never';
 async function refresh(){try{const {accounts}=await api('accounts');document.getElementById('accountsBody').innerHTML=accounts.map(a=>'<tr><td>'+escaped(a.username)+'</td><td>'+a.role+'</td><td>'+(a.enabled?'Enabled':'Disabled')+'</td><td>'+when(a.last_login)+'</td><td>'+when(a.last_active)+'</td><td><button class="secondary-btn" data-password="'+a.id+'">Set password</button> '+(a.role==='admin'?'':'<button class="secondary-btn" data-enable="'+a.id+'" data-value="'+(!a.enabled)+'">'+(a.enabled?'Disable':'Enable')+'</button>')+'</td></tr>').join('');}catch(e){status(e.message);}}
 const status=text=>document.getElementById('accountsStatus').textContent=text;
 async function change(payload){if(busy)return;busy=true;try{await api('accounts',payload);status('Account updated.');await refresh();}catch(e){status(e.message);}finally{busy=false;}}
 document.getElementById('accountsRefresh').onclick=refresh;
 document.getElementById('accountCreate').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;await change({action:'create',username:form.elements.username.value,password:form.elements.password.value});form.elements.password.value='';};
 const reset=document.createElement('dialog');reset.innerHTML='<form><h2>Set password</h2><label>New password <input type="password" autocomplete="new-password" required minlength="10" maxlength="128"></label><p>Only administrators can set passwords. This will sign the account out on all devices.</p><button type="submit">Save password</button><button type="button">Cancel</button></form>';document.body.append(reset);let selectedId;
 reset.querySelector('button[type=button]').onclick=()=>reset.close();reset.querySelector('form').onsubmit=async e=>{e.preventDefault();const input=reset.querySelector('input');await change({action:'password',id:selectedId,password:input.value});input.value='';reset.close();};reset.addEventListener('close',()=>{reset.querySelector('input').value='';});
 section.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.password){selectedId=b.dataset.password;reset.showModal();}if(b?.dataset.enable)change({action:'enabled',id:b.dataset.enable,enabled:b.dataset.value==='true'});});
 const css=document.createElement('style');css.textContent='body:has(#accountsSection.active) .filters{display:none}#accountsSection input{padding:10px;border:1px solid var(--line);border-radius:7px;background:var(--card);color:var(--text)}#accountCreate{display:flex;gap:16px;flex-wrap:wrap;margin:20px 0}#accountsSection :is(td,th){padding:14px;border:1px solid var(--line)}dialog{background:var(--card);color:var(--text);border:1px solid var(--line);border-radius:16px;padding:25px}dialog::backdrop{background:#0008}';document.head.append(css);
})();
