const fs=require('node:fs/promises'),path=require('node:path');
const {hashToken,hashPassword,checkPassword,username,token}=require('./security.cjs');
const SB='https://fuvlhwoauzvgrbakihsj.supabase.co',COOKIE='__Host-wvis_session',ADMIN='lucasngrealme@gmail.com';
const assets=new Set(['index.html','app.js','styles.css','scoring.js','performance.js','model-history.js','price-ranges.js','active-promoters.js','productivity.js','push-models.js','asm-incentives.js','overview-views.js','zero-sellout.js','fullscreen.js','sorting.js','shared-data.js','config.js','accounts.js']);
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
async function sb(route,options={}){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)fail(503,'Account service is not configured.');const r=await fetch(SB+route,{...options,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(25000)});if(!r.ok)fail(r.status===409?409:502,r.status===409?'Username already exists or data changed.':'Account/data service could not complete the request.');if(r.status===204)return null;const payload=await r.text();return payload?JSON.parse(payload):null;}
const db=(table,query='',options={})=>sb('/rest/v1/'+table+query,options);
const safe=u=>({id:u.id,username:u.username,role:u.role,enabled:u.enabled,last_login:u.last_login,last_active:u.last_active});
function sessionToken(req){return (req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(COOKIE+'='))?.slice(COOKIE.length+1)||'';}
async function current(req){const t=sessionToken(req);if(!/^[a-f0-9]{64}$/.test(t))fail(401,'Sign in to continue.');const s=(await db('wvis_sessions','?token_hash=eq.'+hashToken(t)+'&expires_at=gt.'+encodeURIComponent(new Date().toISOString())))[0];if(!s)fail(401,'Session expired. Please sign in.');const u=(await db('wvis_accounts','?id=eq.'+s.account_id))[0];if(!u||!u.enabled||u.version!==s.account_version)fail(401,'Access changed. Please sign in.');return u;}
async function body(req){if(req.body&&typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;let b=req.body;if(!b){const chunks=[];let n=0;for await(const chunk of req){n+=chunk.length;if(n>2*1024*1024)fail(413,'Request too large.');chunks.push(chunk);}b=Buffer.concat(chunks).toString();}try{return JSON.parse(String(b||'{}'));}catch{fail(400,'Invalid request.');}}
function cookie(res,t){res.setHeader('Set-Cookie',COOKIE+'='+t+'; Path=/; HttpOnly; Secure; SameSite=Strict'+(t?'':'; Max-Age=0'));}
function json(res,data,status=200){res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));}
async function login(req,res){const b=await body(req),name=username(b.username),ip=req.headers['x-vercel-forwarded-for']||req.headers['x-forwarded-for']||'unknown';for(const value of ['ip:'+ip,'name:'+name])if(!await sb('/rest/v1/rpc/wvis_login_attempt',{method:'POST',body:JSON.stringify({rate_key:hashToken(value)})}))fail(429,'Too many attempts. Try again in 15 minutes.');const u=(await db('wvis_accounts','?username=eq.'+encodeURIComponent(name)))[0];let ok=false;
 if(u?.enabled&&u.password_hash)ok=await checkPassword(b.password,u.password_hash);
 else if(u?.enabled&&u.role==='admin'&&name===ADMIN&&typeof b.password==='string'&&b.password.length<=128){const r=await fetch(SB+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:ADMIN,password:b.password}),signal:AbortSignal.timeout(15000)});if(r.ok){const auth=await r.json();const check=await fetch(SB+'/rest/v1/rpc/evis_is_admin',{method:'POST',headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+auth.access_token,'Content-Type':'application/json'},body:'{}'});ok=check.ok&&(await check.json())===true;}}
 else await checkPassword(b.password,'00000000000000000000000000000000:'+('00'.repeat(64)));
 if(!ok)fail(401,'Incorrect username or password.');const t=token(),now=new Date().toISOString();await db('wvis_sessions','',{method:'POST',body:JSON.stringify({token_hash:hashToken(t),account_id:u.id,account_version:u.version,expires_at:new Date(Date.now()+8*3600000).toISOString()})});await db('wvis_accounts','?id=eq.'+u.id,{method:'PATCH',body:JSON.stringify({last_login:now,last_active:now})});cookie(res,t);json(res,{account:safe(u)});
}
async function readAsset(name,u,res){if(!assets.has(name))fail(404,'Not found.');let text=await fs.readFile(path.join(__dirname,'dashboard',name),'utf8');if(name==='index.html'){text=text.replace(/(src|href)="([^":/]+\.(?:js|css))"/g,(_,a,n)=>a+'="/api/gateway?op=asset&amp;name='+n+'"');text=text.replace('</head>','<script>window.dashboardAccount='+JSON.stringify(safe(u)).replace(/</g,'\\u003c')+';</script><script defer src="/api/gateway?op=asset&amp;name=accounts.js"></script></head>');}res.setHeader('Content-Type',name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'application/javascript');res.end(text);}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('Vary','Cookie');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Content-Security-Policy',"frame-ancestors 'none'");try{
 const url=new URL(req.url,'https://placeholder'),op=url.searchParams.get('op');if(!['GET','POST'].includes(req.method))fail(405,'Method not allowed.');if(req.method==='POST'){const expected=process.env.DASHBOARD_ORIGIN;if(!expected||req.headers.origin!==expected)fail(403,'Invalid request origin.');}
 if(op==='login'){if(req.method!=='POST')fail(405,'Method not allowed.');return await login(req,res);}
 const u=await current(req);if(op==='session')return json(res,{account:safe(u)});
 if(op==='logout'){if(req.method!=='POST')fail(405,'Method not allowed.');await db('wvis_sessions','?token_hash=eq.'+hashToken(sessionToken(req)),{method:'DELETE'});cookie(res,'');return json(res,{ok:true});}
 if(op==='activity'){if(req.method!=='POST')fail(405,'Method not allowed.');await db('wvis_accounts','?id=eq.'+u.id,{method:'PATCH',body:JSON.stringify({last_active:new Date().toISOString()})});return json(res,{ok:true});}
 if(op==='dashboard'||op==='asset'){if(req.method!=='GET')fail(405,'Method not allowed.');return await readAsset(op==='dashboard'?'index.html':url.searchParams.get('name'),u,res);}
 if(op==='accounts'){if(u.role!=='admin')fail(403,'Administrator access required.');if(req.method==='GET')return json(res,{accounts:(await db('wvis_accounts','?select=id,username,role,enabled,last_login,last_active&order=username')).map(safe)});const b=await body(req);
  if(b.action==='create'){const name=username(b.username);const hash=await hashPassword(b.password);await db('wvis_accounts','',{method:'POST',body:JSON.stringify({username:name,password_hash:hash,role:'viewer'})});}
  else{if(!/^[a-f0-9-]{36}$/.test(b.id||''))fail(400,'Invalid account.');const target=(await db('wvis_accounts','?id=eq.'+b.id))[0];if(!target)fail(404,'Account not found.');const change={version:target.version+1};if(b.action==='password')change.password_hash=await hashPassword(b.password);else if(b.action==='enabled'){if(target.role==='admin')fail(400,'The administrator cannot be disabled.');if(typeof b.enabled!=='boolean')fail(400,'Choose enabled or disabled.');change.enabled=b.enabled;}else fail(400,'Unknown action.');const updated=await db('wvis_accounts','?id=eq.'+b.id+'&version=eq.'+target.version,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(change)});if(!updated.length)fail(409,'Account changed. Refresh and try again.');await db('wvis_sessions','?account_id=eq.'+b.id,{method:'DELETE'});}
  return json(res,{ok:true});
 }
 if(op==='sheet'){if(req.method!=='GET')fail(405,'Method not allowed.');const slot=url.searchParams.get('slot');let id='1AaSTsNKEO0olJ1UxCwtSLpktkSMKvfiDERlBLhWFDkc',tab={fixed:'PREVIOUS MONTHS',current:'CURRENT MONTH'}[slot];if(slot==='hr'){const m=(await db('evis_dataset','?id=eq.1&select=files'))[0];const config=m.files.activePromoters||{url:'https://docs.google.com/spreadsheets/d/1m6k6RlB3hIwMkBC1lJcZwQpB51lyoFUO8zChpvzlCPM',tab:'HR PS STATUS'};id=config.url.match(/\/spreadsheets\/d\/([\w-]+)/)?.[1];tab=config.tab;}if(!id||!tab)fail(400,'Invalid sheet.');const r=await fetch('https://docs.google.com/spreadsheets/d/'+id+'/gviz/tq?tqx=out:csv&headers=1&sheet='+encodeURIComponent(tab),{signal:AbortSignal.timeout(45000)});if(!r.ok)fail(502,'Google Sheet unavailable.');res.setHeader('Content-Type','text/csv');return res.end(await r.text());}
 if(op==='file'){if(req.method!=='GET')fail(405,'Method not allowed.');const name=url.searchParams.get('path');const m=(await db('evis_dataset','?id=eq.1&select=files'))[0];if(!/^[a-f0-9-]{36}\.json\.gz$/.test(name||'')||!Object.values(m.files).some(x=>x?.path===name))fail(404,'File not found.');const r=await fetch(SB+'/storage/v1/object/authenticated/evis-shared/'+name,{headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY}});if(!r.ok)fail(502,'File unavailable.');res.setHeader('Content-Type','application/gzip');return res.end(Buffer.from(await r.arrayBuffer()));}
 if(op==='shared'){const route=url.searchParams.get('path');if(req.method==='GET'&&route==='/rest/v1/evis_dataset?id=eq.1&select=version,updated_at,files')return json(res,await sb(route));if(u.role!=='admin')fail(403,'Administrator access required.');if(req.method!=='POST')fail(405,'Method not allowed.');if(/^\/storage\/v1\/object\/evis-shared\/[a-f0-9-]{36}\.json\.gz$/.test(route||'')){
   let raw=req.body;if(!Buffer.isBuffer(raw)){const chunks=[];let n=0;for await(const part of req){n+=part.length;if(n>2000000)fail(413,'Score file too large.');chunks.push(part);}raw=Buffer.concat(chunks);}if(raw.length>2000000)fail(413,'Score file too large.');
   let file;try{file=JSON.parse(require('node:zlib').gunzipSync(raw,{maxOutputLength:4000000}));}catch{fail(400,'Invalid score file.');}
   if(!Array.isArray(file.rows)||file.rows.length>10000||file.rows.some(r=>typeof r.Model!=='string'||!r.Model.trim()||typeof r.Series!=='string'||!Number.isFinite(Number(r['Points per Unit']))||Number(r['Points per Unit'])<0))fail(400,'Invalid score rows.');
   const out=await fetch(SB+route,{method:'POST',headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/gzip','x-upsert':'false'},body:raw});if(!out.ok)fail(502,'Score upload failed.');return json(res,await out.json());
  }
  const b=await body(req);
  if(route==='/rest/v1/rpc/evis_publish'){if(!b.changes||Object.keys(b.changes).some(k=>k!=='scores'))fail(400,'Only model scores can be uploaded.');return json(res,await sb('/rest/v1/rpc/wvis_publish_scores',{method:'POST',body:JSON.stringify({expected_version:b.expected_version,descriptor:b.changes.scores})}));}
  if(['/rest/v1/rpc/evis_set_price_ranges','/rest/v1/rpc/evis_set_roster'].includes(route))return json(res,await sb(route,{method:'POST',body:JSON.stringify(b)}));
  // Score uploads are handled via a dedicated validated endpoint, never an arbitrary proxy.
  fail(400,'Unsupported shared-data operation.');
 }
 fail(404,'Not found.');
 }catch(e){if(e.status===401){cookie(res,'');if(new URL(req.url,'https://placeholder').searchParams.get('op')==='dashboard'){res.statusCode=302;res.setHeader('Location','/');return res.end();}}json(res,{error:e.status?e.message:'Request failed. Please try again.'},e.status||500);}};
