/* Inventory uses current HR assignments and an independently refreshed stock snapshot. */
(function(root){
 const clean=v=>String(v??'').trim(),key=v=>clean(v).normalize('NFKC').replace(/\s+/g,' ').toUpperCase();
 function csvGrid(text){const rows=[];let row=[],s='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){s+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===','||c==='\n')){row.push(s.replace(/\r$/,''));s='';if(c==='\n'){rows.push(row);row=[];}}else s+=c;}if(s||row.length){row.push(s.replace(/\r$/,''));rows.push(row);}return rows;}
 function activeStores(entries,inventory){
  const codes=new Map(),names=new Map();for(const s of inventory){for(const [map,k] of [[codes,key(s.sid)],[names,key(s.name)]])if(k){if(!map.has(k))map.set(k,[]);map.get(k).push(s);}}
  const out=new Map();let unassigned=0;
  for(const e of entries){if(!clean(e.sid)&&!clean(e.store)){unassigned++;continue;}const matches=e.sid?codes.get(key(e.sid)):names.get(key(e.store));const src=matches?.length===1?matches[0]:null;const id=key(e.sid)||(src?.sid?key(src.sid):'NAME:'+key(e.store));if(out.has(id))continue;
   out.set(id,{id,sid:e.sid||src?.sid||'',name:e.store||src?.name||'',dealer:e.customer||src?.dealer||'Unassigned',area:e.area||src?.area||'Unassigned',subregion:e.asm||src?.subregion||'Unassigned',type:src?.type||'Unclassified',date:src?.date||'',stock:src?.stock||{},missing:!src});
  }return {stores:[...out.values()].sort((a,b)=>a.name.localeCompare(b.name)),unassigned};
 }
 function scope(stores,dealer='ALL',geo='WVIS'){return stores.filter(s=>(dealer==='ALL'||s.dealer===dealer)&&(geo==='WVIS'||s.area===geo||s.subregion===geo));}
 function stats(stores,model){let stocked=0,unknown=0,qty=0;for(const s of stores){const v=s.stock[model];if(v==null){unknown++;continue;}if(v>0)stocked++;qty+=v;}return {count:stores.length,stocked,unknown,qty,rate:stores.length?100*stocked/stores.length:null};}
 function defaults(models){return models.filter(m=>/^(?:HP\.)?\s*(?:Note\s*80|C100i|C100\s*4G|16T|16(?:\s|Pro))/i.test(m)||/(?:TechLife|Nexal).*Pad|Nexal/i.test(m));}
 const api={csvGrid,activeStores,scope,stats,defaults};if(typeof module!=='undefined'&&module.exports){module.exports=api;return;}root.WvisInventory=api;
 const section=document.getElementById('inventorySection');if(!section)return;
 let data=null,error='',busy=false,view='summary',saved={summaryDealer:'ALL',summaryModels:null,dealer:'ALL',dealerModels:['','','','','',''],geo:'',store:'',panels:[{geo:'WVIS',dealer:'ALL',model:''},{geo:'WVIS',dealer:'ALL',model:''}]};
 try{Object.assign(saved,JSON.parse(localStorage.getItem('wvis.inventory.options')||'{}'));}catch{}
 const esc=s=>escapeHtml(String(s??'')),persist=()=>{try{localStorage.setItem('wvis.inventory.options',JSON.stringify(saved));}catch{}},options=(values,value,blank)=>`${blank?'<option value="">'+esc(blank)+'</option>':''}`+values.map(v=>'<option value="'+esc(v)+'"'+(v===value?' selected':'')+'>'+esc(v==='ALL'?'All dealers':v)+'</option>').join('');
 const select=(id,label,values,value,blank)=>'<label>'+esc(label)+'<select data-inv="'+id+'" aria-label="'+esc(label)+'">'+options(values,value,blank)+'</select></label>';
 const modelSelect=(id,value,i)=>'<select data-inv="'+id+'" aria-label="Model column '+(i+1)+'">'+options(data.models,value,'Select model')+'</select>';
 const number=v=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
 const qty=(s,m)=>!m?'<td></td>':'<td class="'+(s.stock[m]===0?'inv-zero':'')+'">'+number(s.stock[m])+'</td>';
 const table=(headers,rows)=>'<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div>';
 const empty=n=>'<tr><td colspan="'+n+'">NO PS STORE</td></tr>';
 function render(){
  const roster=root.evisRoster?.getRoster();
  section.innerHTML='<article class="card table-card"><div class="card-head"><h2>PS Store Inventory</h2><button type="button" class="secondary-btn" data-inv-refresh '+(busy?'disabled':'')+'>'+(busy?'Checking…':'Refresh inventory')+'</button></div><div class="inv-tabs" role="group" aria-label="Inventory views">'+[['summary','Store Coverage Summary'],['zero','Zero Stocks Store Check'],['dealer','per DEALER CHECKING'],['store','per STORE CHECKING']].map(([id,label])=>'<button class="secondary-btn" data-inv-view="'+id+'" aria-pressed="'+(view===id)+'">'+label+'</button>').join('')+'</div><p class="score-note" role="status">'+esc(error||(data?'INVENTORY per STORE · Checked '+new Date(data.checkedAt).toLocaleString():'Loading inventory…'))+'</p></article><div id="inventoryContent"></div>';
  const content=document.getElementById('inventoryContent');if(!data||!roster){content.innerHTML='<p>'+(!roster?'Waiting for the current active-promoter roster.':'')+'</p>';return;}
  const joined=activeStores(roster.entries,data.stores),stores=joined.stores,dealers=['ALL',...new Set([...stores,...data.stores].map(s=>s.dealer).filter(Boolean))].sort((a,b)=>a==='ALL'?-1:b==='ALL'?1:a.localeCompare(b)),subs=[...new Set([...stores,...data.stores].map(s=>s.subregion).filter(Boolean))].sort(),geos=['WVIS','NEGROS','PANAY','EVIS',...subs.filter(s=>!['WVIS','NEGROS','PANAY','EVIS'].includes(s))];
  saved.summaryModels??=[...defaults(data.models),'','','','',''];saved.summaryModels=saved.summaryModels.map(m=>data.models.includes(m)?m:'');
  content.innerHTML='<p class="score-note">Unique stores assigned to current ACTIVE promoters. Inventory uses the filters below, independently of sales-month filters. — means inventory unavailable.'+(joined.unassigned?' '+joined.unassigned+' active promoters have no store assignment.':'')+(stores.some(s=>s.missing)?' '+stores.filter(s=>s.missing).length+' eligible stores have no unique matching inventory record.':'')+'</p>';
  if(view==='summary'){
   if(!dealers.includes(saved.summaryDealer))saved.summaryDealer='ALL';const list=scope(stores,saved.summaryDealer);
   const controls='<div class="inv-controls">'+select('summaryDealer','Dealer',dealers,saved.summaryDealer)+'</div>';
   const groups=[['WVIS',list],...['NKA','RKA','SME',...new Set(list.map(s=>s.type).filter(t=>!['NKA','RKA','SME'].includes(t)))].map(t=>[t,list.filter(s=>s.type===t)]),...['NEGROS','PANAY','EVIS'].map(a=>[a,list.filter(s=>s.area===a)]),...subs.map(s=>[s,list.filter(x=>x.subregion===s)])];
   const headers=['Dealer type / Area / Subregion','# of PS Stores',...saved.summaryModels.map((m,i)=>modelSelect('summaryModel:'+i,m,i))];
   for(const mode of ['coverage','quantity']){const rows=groups.map(([label,items])=>'<tr><th>'+esc(label)+'</th><td>'+items.length+'</td>'+saved.summaryModels.map(m=>{if(!m)return '<td></td>';const st=stats(items,m);if(!st.count)return '<td>—</td>';const text=mode==='coverage'?st.rate.toFixed(2)+'%':number(st.qty);const color=mode==='coverage'?' style="background:hsl('+Math.round(st.rate*1.2)+' 45% 86%);color:#17202a"':'';return '<td'+color+' title="'+st.stocked+' of '+st.count+' stores with stock; '+st.unknown+' unavailable">'+text+(st.unknown?' *':'')+'</td>';}).join('')+'</tr>').join('');content.innerHTML+='<article class="card table-card"><h2>'+(mode==='coverage'?'Stores with Stocks (%)':'Inventory (Qty)')+'</h2>'+ (mode==='coverage'?controls:'')+table(headers,rows)+'<p class="score-note">* Incomplete inventory. Coverage includes all eligible stores in the denominator; quantities sum reported stock only.</p></article>';}
  }else if(view==='zero'){
   content.innerHTML+='<div class="inv-panels">'+saved.panels.map((p,i)=>{if(!geos.includes(p.geo))p.geo='WVIS';if(!dealers.includes(p.dealer))p.dealer='ALL';if(!data.models.includes(p.model))p.model=data.models[0];const list=scope(stores,p.dealer,p.geo),zeros=list.filter(s=>s.stock[p.model]===0),unknown=list.filter(s=>s.stock[p.model]==null);return '<article class="card table-card"><div class="inv-controls">'+select('panel:'+i+':geo','Subregion',geos,p.geo)+select('panel:'+i+':model','Model',data.models,p.model)+select('panel:'+i+':dealer','Dealer',dealers,p.dealer)+'</div>'+table(['Store','Dealer','Dealer Coverage (%)'],zeros.map(s=>{const st=stats(scope(stores,s.dealer,p.geo),p.model);return '<tr><td>'+esc(s.name)+'</td><td>'+esc(s.dealer)+'</td><td>'+st.rate.toFixed(2)+'%'+(st.unknown?' *':'')+'</td></tr>';}).join('')||'<tr><td colspan="3">'+(!list.length?'NO PS STORE':unknown.length?'No confirmed zero-stock stores; inventory incomplete.':'ALL STORES COVERED')+'</td></tr>')+(unknown.length?'<p class="score-note">'+unknown.length+' stores have unavailable inventory and need checking.</p>':'')+'</article>';}).join('')+'</div>';
  }else if(view==='dealer'){
   if(!dealers.includes(saved.dealer))saved.dealer='ALL';const list=scope(stores,saved.dealer);content.innerHTML+='<article class="card table-card"><div class="inv-controls">'+select('dealer','Dealer',dealers,saved.dealer)+'</div>'+table(['Subregion','Store',...saved.dealerModels.map((m,i)=>modelSelect('dealerModel:'+i,m,i)),'Last Inventory Date'],list.map(s=>'<tr><td>'+esc(s.subregion)+'</td><td>'+esc(s.name)+'</td>'+saved.dealerModels.map(m=>qty(s,m)).join('')+'<td>'+esc(s.date||'Unavailable')+'</td></tr>').join('')||empty(9))+'</article>';
  }else{
   if(!subs.includes(saved.geo))saved.geo=subs[0]||'';const list=stores.filter(s=>s.subregion===saved.geo);if(!list.some(s=>s.id===saved.store))saved.store=list[0]?.id||'';const s=list.find(s=>s.id===saved.store);content.innerHTML+='<article class="card table-card"><div class="inv-controls">'+select('geo','Subregion',subs,saved.geo)+'<label>Store<select data-inv="store" aria-label="Store">'+list.map(s=>'<option value="'+esc(s.id)+'"'+(s.id===saved.store?' selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select></label></div>'+(s?'<p><strong>Dealer:</strong> '+esc(s.dealer)+' · <strong>Last Inventory Date:</strong> '+esc(s.date||'Unavailable')+'</p>'+table(['Model','Inventory'],data.models.map(m=>'<tr><td>'+esc(m)+'</td>'+qty(s,m)+'</tr>').join('')):'<p>NO PS STORE</p>')+'</article>';
  }
 }
 async function load(){if(busy)return;busy=true;render();try{const r=await fetch('/api/gateway?op=inventory',{cache:'no-store'});if(!r.ok)throw new Error('Inventory could not be loaded. Try Refresh inventory.');data=await r.json();error='';}catch(e){error=(data?'Showing last loaded inventory. ':'')+e.message;}finally{busy=false;render();}}
 section.addEventListener('click',e=>{const b=e.target.closest('[data-inv-view]');if(b){view=b.dataset.invView;render();}if(e.target.closest('[data-inv-refresh]'))load();});
 section.addEventListener('change',e=>{const id=e.target.dataset.inv;if(!id)return;const [kind,a,b]=id.split(':');if(kind==='panel')saved.panels[+a][b]=e.target.value;else if(kind==='summaryModel')saved.summaryModels[+a]=e.target.value;else if(kind==='dealerModel')saved.dealerModels[+a]=e.target.value;else saved[kind]=e.target.value;persist();render();});
 const style=document.createElement('style');style.textContent='#inventorySection .inv-tabs,#inventorySection .inv-controls{display:flex;flex-wrap:wrap;gap:12px;margin:14px 0}#inventorySection [aria-pressed="true"]{background:#ffcf19;color:#171717}#inventorySection label{display:flex;flex-direction:column;gap:6px;flex:1;min-width:180px}#inventorySection select{width:100%;min-width:130px;padding:9px;border:1px solid #cbd1db;border-radius:7px;background:var(--card,#fff);color:inherit}#inventorySection th select{font-size:12px;width:155px}#inventorySection table{width:100%;font-variant-numeric:tabular-nums}#inventorySection td{white-space:nowrap}#inventorySection td:first-child,#inventorySection td:nth-child(2){white-space:normal;min-width:140px}#inventorySection .inv-zero{background:#fbd8db;color:#ae1924;font-weight:700}#inventorySection .inv-panels{display:grid;grid-template-columns:1fr 1fr;gap:16px}#inventorySection .inv-panels>*{min-width:0}body:has(#inventorySection.active) .filters{display:none}@media(max-width:900px){#inventorySection .inv-panels{grid-template-columns:1fr}}';document.head.append(style);
 renderInventory=()=>{};root.evisInventory={render};
 document.addEventListener('DOMContentLoaded',()=>{const nav=document.querySelector('[data-section="inventory"]');nav.textContent='Inventory';nav.addEventListener('click',()=>{render();if(!data)load();});document.getElementById('refreshBtn').addEventListener('click',()=>{if(section.classList.contains('active'))load();});});
 setInterval(()=>{if(section.classList.contains('active')&&document.visibilityState==='visible')load();},60000);
})(typeof window==='undefined'?{}:window);
