// Daily zero sellout: current HR roster, calendar-day coverage, and month-bounded streaks.
function zeroSelloutReport(all,entries,month,today,series,measure,range){
 const end=month===today.slice(0,7)?+today.slice(8):month<today.slice(0,7)?new Date(+month.slice(0,4),+month.slice(5),0).getDate():0;
 const dates=Array.from({length:end},(_,i)=>month+'-'+String(i+1).padStart(2,'0')),coverage=new Set(),totals=new Map(entries.map(e=>[e.key,new Map()]));
 const byId=new Map(entries.filter(e=>e.id).map(e=>[e.id,e])),byName=new Map(entries.map(e=>[rosterName(e.name),e]));
 for(const r of all){if(!r._date||isNaN(r._date))continue;const d=modelMonthKey(r._date)+'-'+String(r._date.getDate()).padStart(2,'0');if(!dates.includes(d))continue;coverage.add(d);
  if(series!=='ALL'&&r._series!==series)continue;if(measure==='premium'&&r._priceRange!==range)continue;
  const id=rosterCode(r._ps),named=byName.get(rosterName(find(r,'PS Name','Promoter Name'))),e=byId.get(id)||((!id||!named?.id)&&named);if(!e)continue;
  const t=totals.get(e.key);t.set(d,(t.get(d)||0)+r._qty);
 }
 const anchor=[...dates].reverse().find(d=>d<today);
 const people=entries.map(e=>{const t=totals.get(e.key),zero=new Set(dates.filter(d=>coverage.has(d)&&(t.get(d)||0)<=0));let streak=0;
  if(anchor)for(let i=dates.indexOf(anchor);i>=0;i--){if(!coverage.has(dates[i])||!zero.has(dates[i]))break;streak++;}
  return {...e,zero,streak};});
 function group(key){const groups=new Map();for(const p of people){const label=key==='asm'?[p.area,p.asm].filter(Boolean).join(' / '):p[key];const name=label||'Unassigned';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(p);}return [...groups].sort((a,b)=>a[0].localeCompare(b[0]));}
 return {dates:dates.reverse(),coverage,anchor,people,groups:{area:group('area'),asm:group('asm'),customer:group('customer')}};
}
(()=>{
 let view='daily',measure='all',initialized=false;
 const nav=document.createElement('button');nav.className='nav-item';nav.dataset.section='zeroSellout';nav.textContent='Daily Zero Sellout';document.querySelector('[data-section="productivity"]').after(nav);
 const section=document.createElement('section');section.className='dashboard-section';section.id='zeroSelloutSection';
 section.innerHTML='<article class="card table-card"><div class="card-head"><h2>Daily Zero Sellout</h2></div><div class="zero-toggle-row"><div role="group" aria-label="Zero sellout view"><button class="secondary-btn" data-zero-view="daily" aria-pressed="true">Daily Zero Sellout</button><button class="secondary-btn" data-zero-view="streak" aria-pressed="false">Consecutive Zero-Sales Days</button></div><div role="group" aria-label="Sales measure"><button class="secondary-btn" data-zero-measure="all" aria-pressed="true">All Smartphone Sales</button><button class="secondary-btn" data-zero-measure="premium" aria-pressed="false">more Php 13000</button></div></div><div id="zeroContext" role="status"></div><div class="zero-kpis" id="zeroKpis"></div><details class="zero-method"><summary>How to read this table</summary><div>Counts use today’s ACTIVE HR roster and current HR Area, Subregion and Dealer assignments, including promoters with no sales. Series changes sales only, not headcount. Daily cells show count (% of ACTIVE PS). A date is available when the sales source contains at least one row that day, before filtering. This cannot confirm every store has submitted its sales. Missing dates show No data and break streaks. Today is provisional. Streak buckets are exclusive and end on the day before checking for the current month, or month-end for past months; Columns count exactly 2 through 7 days; longer streaks are excluded. Rest days and leave are not excluded.</div></details></article>'+[['area','Area'],['asm','Subregion'],['customer','Dealer']].map(([key,label])=>'<article class="card table-card"><div class="card-head"><h2>Zero Sellout by '+label+'</h2></div><div class="table-wrap zero-table-wrap"><table data-no-sort aria-label="Zero Sellout by '+label+'"><thead id="zeroHead'+key+'"><tr><th>'+label+'</th><th>ACTIVE PS</th></tr></thead><tbody id="zeroBody'+key+'"></tbody><tfoot id="zeroTotal'+key+'"></tfoot></table></div></article>').join('');
 $('overviewSection').after(section);
 function renderZero(){
  const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  if(section.classList.contains('active')&&!initialized&&$('monthFilter').options.length){const current=today.slice(0,7);if(![...$('monthFilter').options].some(o=>o.value===current))$('monthFilter').add(new Option(monthName(current),current));$('monthFilter').value=current;initialized=true;}
  const month=selected('monthFilter');if(month==='ALL'){$('periodLabel').textContent='Loading sales dates…';return;}if(section.classList.contains('active'))$('periodLabel').textContent=monthName(month)+' · checked '+today;
  const roster=window.evisRoster.getRoster(),series=selected('seriesFilter'),range=window.evisPriceRanges.getRanges().find(r=>r.name.toLowerCase().replace(/[^a-z0-9]/g,'')==='morephp13000')?.name;
  const ready=!!roster&&(measure!=='premium'||!!range),r=zeroSelloutReport(salesEnriched(),roster?.entries||[],month,today,series,measure,range);
  const label=d=>new Date(d+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}),percent=(n,total)=>fmt(n)+' <span class="zero-percent">('+fmt(total?n/total*100:0,1)+'%)</span>';
  $('zeroContext').textContent=!roster?'Loading ACTIVE HR roster…':!ready?'Define “more Php 13000” to use this measure.':view==='daily'?monthName(month)+' · newest date first · '+(series==='ALL'?'All series':series):'Current streaks as of '+(r.anchor?label(r.anchor):'No completed date available')+' · '+(r.anchor&&!r.coverage.has(r.anchor)?'No data at cutoff · ':'')+(series==='ALL'?'All series':series);
  const latest=r.dates.find(d=>r.coverage.has(d)),streak=r.people.filter(p=>p.streak>=2&&p.streak<=7).length;
  $('zeroKpis').innerHTML=[['ACTIVE promoters',r.people.length],['Latest sales date',latest?label(latest):'No data'],['2–7 days without sales',ready&&r.anchor&&r.coverage.has(r.anchor)?streak:'—']].map(([l,v])=>'<div><span>'+l+'</span><strong>'+v+'</strong></div>').join('');
  function cells(people){if(view==='daily')return r.dates.map(d=>'<td class="'+(d===today?'zero-today':'')+'">'+(!ready?'—':!r.coverage.has(d)?'<span class="zero-unavailable">No data</span>':percent(people.filter(p=>p.zero.has(d)).length,people.length))+'</td>').join('');return [2,3,4,5,6,7].map(n=>'<td class="zero-streak-'+n+'">'+(!ready||!r.anchor||!r.coverage.has(r.anchor)?'No data':percent(people.filter(p=>p.streak===n).length,people.length))+'</td>').join('');}
  for(const [key,title] of [['area','Area'],['asm','Subregion'],['customer','Dealer']]){
   $('zeroHead'+key).innerHTML='<tr><th>'+title+'</th><th>ACTIVE PS</th>'+(view==='daily'?r.dates.map(d=>'<th>'+label(d)+(d===today?'<small>In progress</small>':'')+'</th>').join(''):[2,3,4,5,6,7].map(n=>'<th class="zero-streak-'+n+'">'+n+' days</th>').join(''))+'</tr>';
   $('zeroBody'+key).innerHTML=r.groups[key].map(([name,people])=>'<tr><td>'+escapeHtml(name)+'</td><td>'+people.length+'</td>'+cells(people)+'</tr>').join('')||'<tr><td colspan="'+(view==='daily'?r.dates.length+2:8)+'">Waiting for ACTIVE promoters</td></tr>';
   $('zeroTotal'+key).innerHTML='<tr><th>WVIS</th><td>'+r.people.length+'</td>'+cells(r.people)+'</tr>';
  }
 }
 section.querySelectorAll('[data-zero-view]').forEach(b=>b.onclick=()=>{view=b.dataset.zeroView;section.querySelectorAll('[data-zero-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderZero();});
 section.querySelectorAll('[data-zero-measure]').forEach(b=>b.onclick=()=>{measure=b.dataset.zeroMeasure;section.querySelectorAll('[data-zero-measure]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderZero();});
 const before=render;render=()=>{before();renderZero();};
 nav.addEventListener('click',()=>queueMicrotask(renderZero));setInterval(()=>{if(section.classList.contains('active')&&document.visibilityState==='visible')renderZero();},60000);
 
 const style=document.createElement('style');style.textContent='body:has(#zeroSelloutSection.active) .filters{grid-template-columns:repeat(2,minmax(160px,280px));justify-content:start}body:has(#zeroSelloutSection.active) .filters .filter-group:not(:has(#monthFilter)):not(:has(#seriesFilter)),body:has(#zeroSelloutSection.active) .filter-actions{display:none!important}.zero-preview-tag{font-size:10px;letter-spacing:.12em;color:#9a7a00;font-weight:800;margin-bottom:12px}.zero-toggle-row{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.zero-toggle-row [role=group]{display:flex;gap:6px;flex-wrap:wrap}.zero-toggle-row button[aria-pressed=true]{background:#fff2bc;border-color:#d4ad20}.zero-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:18px}.zero-kpis>div{padding:16px;border:1px solid var(--line);border-radius:10px}.zero-kpis span{font-size:11px;color:var(--muted);display:block}.zero-kpis strong{font-size:22px;display:block;margin-top:8px}#zeroContext{margin-top:15px;font-size:12px;color:var(--muted)}.zero-method{font-size:11px;color:var(--muted);margin-top:15px;line-height:1.7}.zero-method summary{cursor:pointer}.zero-table-wrap{max-height:450px}.zero-table-wrap table{border-collapse:separate;border-spacing:0}.zero-table-wrap :is(td,th){text-align:center;white-space:nowrap;border-right:1px solid var(--line);min-width:115px}.zero-table-wrap tr>:first-child{text-align:left;position:sticky;left:0;z-index:2;background:var(--card);min-width:190px;max-width:300px;white-space:normal}.zero-table-wrap thead th{position:sticky;top:0;z-index:3}.zero-table-wrap thead th:first-child{z-index:4}.zero-table-wrap small{display:block;text-transform:none;color:#977000;margin-top:5px}.zero-percent{font-size:10px;color:var(--muted)}.zero-unavailable{color:var(--muted);font-size:10px}.zero-table-wrap .zero-today{background:#fff9e5}.zero-table-wrap .zero-streak-2{background:#fff8df}.zero-table-wrap .zero-streak-3{background:#fff0db}.zero-table-wrap .zero-streak-4{background:#ffe4d6}.zero-table-wrap :is(.zero-streak-5,.zero-streak-6,.zero-streak-7){background:#fbe3e3}html[data-theme=night] .zero-table-wrap .zero-today{background:#35301f}html[data-theme=night] .zero-table-wrap .zero-streak-2{background:#393421}html[data-theme=night] .zero-table-wrap .zero-streak-3{background:#483820}html[data-theme=night] .zero-table-wrap .zero-streak-4{background:#4b3026}html[data-theme=night] .zero-table-wrap :is(.zero-streak-5,.zero-streak-6,.zero-streak-7){background:#4a272e}html[data-theme=night] :is(.zero-preview-tag,.zero-table-wrap small){color:#f4d474}@media(max-width:600px){.zero-kpis{grid-template-columns:1fr}.zero-table-wrap tr>:first-child{min-width:125px}}';document.head.append(style);
})();
